### ISSUE TITLE
steps to run?

### ISSUE THREAD

**Issue by DesaleF** [joshuawillman/Photo_Editor#1]
Thank you for sharing your work! I want to use it and I can't find any requirent.txt or other file to setup my environment to run the code. Can you provide me your conda environment or docker to try out your code faster?

Thank you

**Comment by joshuawillman** [comment]
This was a project that I was working on, but got distracted by other projects and work. I need to update the code so that it can be run on either PyQt5 or PyQt6. 
For now, there are a number of bugs in the code. The code also needs to be refactored. 

Running the code can be achieved by simply running the code in your shell.
